version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck  # includes gosimple in v2.x
    - unused
    - misspell
    - goconst
    - gocyclo
    - dupl
    - gosec
    - unconvert
    - prealloc

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
  gocyclo:
    min-complexity: 18
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    excludes:
      - G201  # SQL string formatting with placeholders is safe
      - G202  # SQL string concatenation - filters are sanitized

issues:
  exclude-dirs:
    - vendor
    - web
    - scripts  # Standalone scripts with their own main functions
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - goconst
    # Exclude cyclomatic complexity for specific pre-existing complex functions
    - linters:
        - gocyclo
      text: "GetExecutiveReport|ExportExecutiveReport"
