# GitHub Migrator - Default Configuration
# This is the default configuration file for local development

server:
  port: 8080

database:
  type: sqlite
  dsn: ./data/migrator.db

# Source repository system (where to migrate FROM)
# Only GitHub to GitHub migrations are supported
# Source can be: GitHub.com or GitHub Enterprise Server
source:
  type: github
  base_url: "https://api.github.com"
  token: "${GITHUB_SOURCE_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # When configured: GitHub App used for discovery, PAT used for migrations
  # 
  # app_installation_id is OPTIONAL:
  #   - Provide installation ID: Uses that installation's token for enterprise operations
  #   - Omit installation ID: System uses GitHub App Installations API to discover
  #     all organizations where the app is installed, then creates per-org clients
  #     (best for multi-org GitHub Apps, requires JWT auth)
  # app_id: 1234567
  # app_private_key: "/path/to/private-key.pem"
  # app_installation_id: 1234567  # Optional: omit to auto-discover all app installations

# Destination repository system (where to migrate TO)
# Only GitHub to GitHub migrations are supported
# Destination can be: GitHub.com, GitHub with data residency, or GitHub Enterprise Cloud
# Note: Destination organization can be customized per-repository via API/UI
destination:
  type: github
  base_url: "https://api.github.com"
  token: "${GITHUB_DEST_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # When configured: GitHub App used for discovery, PAT used for migrations
  # app_id: 123456
  # app_private_key: "/path/to/private-key.pem"
  # app_installation_id: 789012

# Migration worker configuration
migration:
  # Number of parallel migration workers (default: 5)
  workers: 5
  # Polling interval in seconds (default: 30)
  poll_interval_seconds: 30
  # When to run post-migration validation: never, production_only, dry_run_only, always (default: production_only)
  post_migration_mode: "production_only"
  # What to do if destination repo exists: fail, skip, delete (default: fail)
  dest_repo_exists_action: "fail"
  
  # Visibility transformation rules (default: all repos become private)
  # Controls how repository visibility is mapped from source to destination
  visibility_handling:
    # How to handle public repositories: public, internal, or private (default: private)
    # Note: EMU and data residency environments do NOT support public repositories
    public_repos: "private"
    # How to handle internal repositories: internal or private (default: private)
    internal_repos: "private"

logging:
  level: debug
  format: text
  output_file: ./logs/migrator.log
  max_size: 100
  max_backups: 3
  max_age: 28

# Authentication (optional, disabled by default)
auth:
  enabled: false
  # github_oauth_client_id: "Iv1.abcd1234"
  # github_oauth_client_secret: "your-secret-here"
  # callback_url: "http://localhost:8080/api/v1/auth/callback"
  # session_secret: "your-random-secret-key-here"
  # session_duration_hours: 24
  # authorization_rules:
  #   # Require user to be member of these orgs (empty = no requirement)
  #   require_org_membership:
  #     - "my-github-org"
  #   # Require user to be member of these teams (empty = no requirement)
  #   # Format: "org/team-slug"
  #   require_team_membership:
  #     - "my-github-org/migration-admins"
  #   # Require user to be enterprise admin (default: false)
  #   require_enterprise_admin: false
  #   # Enterprise slug to check admin status (required if require_enterprise_admin is true)
  #   require_enterprise_slug: "my-enterprise"
