# GitHub Migration Server - Default Configuration
# This is the default configuration file for local development

server:
  port: 8080

database:
  type: sqlite
  dsn: ./data/migrator.db

# Source repository system (where to migrate FROM)
# Only GitHub to GitHub migrations are supported
# Source can be: GitHub.com or GitHub Enterprise Server
source:
  type: github
  base_url: "https://api.github.com"
  token: "${GITHUB_SOURCE_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # When configured: GitHub App used for discovery, PAT used for migrations
  # app_id: 123456
  # app_private_key: "/path/to/private-key.pem"
  # app_installation_id: 789012

# Destination repository system (where to migrate TO)
# Only GitHub to GitHub migrations are supported
# Destination can be: GitHub.com, GitHub with data residency, or GitHub Enterprise Server
# Note: Destination organization can be customized per-repository via API/UI
destination:
  type: github
  base_url: "https://api.github.com"
  token: "${GITHUB_DEST_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # When configured: GitHub App used for discovery, PAT used for migrations
  # app_id: 123456
  # app_private_key: "/path/to/private-key.pem"
  # app_installation_id: 789012

# Migration worker configuration
migration:
  # Number of parallel migration workers (default: 5)
  workers: 5
  # Polling interval in seconds (default: 30)
  poll_interval_seconds: 30
  # When to run post-migration validation: never, production_only, dry_run_only, always (default: production_only)
  post_migration_mode: "production_only"
  # What to do if destination repo exists: fail, skip, delete (default: fail)
  dest_repo_exists_action: "fail"

logging:
  level: debug
  format: text
  output_file: ./logs/migrator.log
  max_size: 100
  max_backups: 3
  max_age: 28
