# GitHub Migrator - Configuration Example
# This file documents all available configuration options
# Copy this file to config.yaml and customize for your environment

# =============================================================================
# Server Configuration
# =============================================================================
server:
  # HTTP server port (default: 8080)
  port: 8080

# =============================================================================
# Database Configuration
# =============================================================================
database:
  # Database type: "sqlite" or "postgres"
  # - sqlite: Recommended for development and small deployments
  # - postgres: Recommended for production
  type: sqlite
  
  # Database connection string (DSN)
  # SQLite example:
  dsn: ./data/migrator.db
  
  # PostgreSQL example:
  # dsn: postgres://user:password@localhost:5432/migrator?sslmode=disable
  
  # Or use environment variable:
  # dsn: "${DATABASE_URL}"

# =============================================================================
# Source Repository System Configuration
# =============================================================================
# This is where you're migrating FROM
# Only GitHub to GitHub migrations are currently supported
source:
  # Source system type
  # Only "github" is supported
  type: github
  
  # API base URL
  # For GitHub Enterprise Server: https://github.company.com/api/v3
  # For GitHub.com: https://api.github.com
  base_url: "https://github.company.com/api/v3"
  
  # Personal Access Token (PAT) - REQUIRED
  # This token is REQUIRED for all migration operations
  # If GitHub App is configured, PAT is used for migrations only
  # Required permissions:
  # - Organization admin access (both source and destination)
  # - Scopes: repo, read:org, read:user, admin:org
  token: "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  
  # ==========================================================================
  # GitHub App Authentication (Optional but Recommended for Large Migrations)
  # ==========================================================================
  # Benefits:
  # - 5,000 requests/hour PER installation vs 5,000/hour total with PAT
  # - Better isolation with per-organization tokens
  # - Parallel organization processing for enterprise migrations
  # - Separation of concerns: App for discovery, PAT for migrations
  #
  # Two Operation Modes:
  #
  # MODE 1: With Installation ID (Simpler)
  #   Best for: Single org, testing, GitHub Apps installed on one organization
  #   Behavior: Uses that installation's token for all API operations
  #   
  #   app_id: 123456
  #   app_private_key: "/path/to/private-key.pem"  # or inline PEM string
  #   app_installation_id: 789012  # Provide for single-org mode
  #
  # MODE 2: Without Installation ID (Enterprise Multi-Org)
  #   Best for: GitHub Enterprise Apps, multi-org migrations
  #   Behavior: Auto-discovers all installations via JWT, creates per-org clients,
  #             processes organizations in parallel (5 workers by default)
  #   
  #   app_id: 123456
  #   app_private_key: "/path/to/private-key.pem"  # or inline PEM string
  #   # app_installation_id omitted - system auto-discovers
  #
  # Private Key Options:
  # 1. File path: "/path/to/private-key.pem"
  # 2. Inline PEM: "-----BEGIN RSA PRIVATE KEY-----\nMIIE...\n-----END RSA PRIVATE KEY-----"
  # 3. Environment variable: "${GHMIG_SOURCE_APP_PRIVATE_KEY}"
  #
  # See OPERATIONS.md for complete setup guide including:
  # - Creating GitHub Apps
  # - Configuring permissions
  # - Finding installation IDs
  # - Troubleshooting

# =============================================================================
# Destination Repository System Configuration
# =============================================================================
# This is where you're migrating TO
# Only GitHub to GitHub migrations are currently supported
destination:
  # Destination system type
  # Only "github" is supported
  type: github
  
  # API base URL
  # For GitHub.com: https://api.github.com
  # For GitHub with data residency: https://api.github.com
  # For GitHub Enterprise Server: https://github.company.com/api/v3
  base_url: "https://api.github.com"
  
  # Personal Access Token (PAT) - REQUIRED
  # This token is REQUIRED for all migration operations
  # If GitHub App is configured, PAT is used for migrations only
  # Required permissions:
  # - Organization admin access (both source and destination)
  # - Scopes: repo, admin:org, workflow
  token: "ghp_yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
  
  # ==========================================================================
  # GitHub App Authentication (Optional but Recommended for Large Migrations)
  # ==========================================================================
  # Same configuration options as source above.
  # Benefits:
  # - 5,000 requests/hour PER installation vs 5,000/hour total with PAT
  # - Better isolation with per-organization tokens
  # - Parallel organization processing for enterprise migrations
  # - Separation of concerns: App for discovery, PAT for migrations
  #
  # MODE 1: With Installation ID (Simpler)
  #   app_id: 123456
  #   app_private_key: "/path/to/private-key.pem"
  #   app_installation_id: 789012
  #
  # MODE 2: Without Installation ID (Enterprise Multi-Org)
  #   app_id: 123456
  #   app_private_key: "/path/to/private-key.pem"
  #   # app_installation_id omitted for auto-discovery
  #
  # See OPERATIONS.md for complete setup guide

# =============================================================================
# Migration Worker Configuration
# =============================================================================
migration:
  # Number of parallel migration workers
  # Higher values = faster migrations but more API rate limit usage
  # Recommended: 5-10 for most deployments
  # Default: 5
  workers: 5
  
  # Polling interval in seconds
  # How often workers check for new repositories to migrate
  # Default: 30
  poll_interval_seconds: 30
  
  # Post-migration validation mode
  # When to run validation after migration completes:
  # - "never": No validation
  # - "production_only": Validate only production migrations (recommended)
  # - "dry_run_only": Validate only dry runs
  # - "always": Validate all migrations
  # Default: "production_only"
  post_migration_mode: "production_only"
  
  # What to do if destination repository already exists
  # Options:
  # - "fail": Fail the migration (safest, recommended)
  # - "skip": Skip this repository and continue
  # - "delete": Delete the existing destination repo and recreate (dangerous!)
  # Default: "fail"
  dest_repo_exists_action: "fail"

# =============================================================================
# Logging Configuration
# =============================================================================
logging:
  # Log level: "debug", "info", "warn", "error"
  # - debug: Verbose logging, includes all operations
  # - info: Standard logging (recommended for production)
  # - warn: Only warnings and errors
  # - error: Only errors
  # Default: "info"
  level: info
  
  # Log format: "json" or "text"
  # - json: Structured JSON logs (recommended for production)
  # - text: Human-readable format (good for development)
  # Default: "json"
  format: json
  
  # Log file path
  # Logs are rotated automatically based on settings below
  # Default: "./logs/migrator.log"
  output_file: ./logs/migrator.log
  
  # Maximum log file size in megabytes before rotation
  # Default: 100
  max_size: 100
  
  # Maximum number of old log files to retain
  # Default: 3
  max_backups: 3
  
  # Maximum number of days to retain old log files
  # Default: 28
  max_age: 28

# =============================================================================
# Authentication & Authorization (Optional)
# =============================================================================
# IMPORTANT: Authentication is DISABLED by default for backward compatibility
# Enable this for production deployments to control who can access the system
auth:
  # Enable/disable authentication
  # When disabled: Open access to all endpoints (default for dev/testing)
  # When enabled: Requires GitHub OAuth authentication
  # Default: false
  enabled: false
  
  # GitHub OAuth Application Configuration
  # Required when auth.enabled = true
  # Create an OAuth App at:
  # - GitHub.com: https://github.com/settings/developers
  # - GitHub Enterprise: https://your-ghes/settings/developers
  # github_oauth_client_id: "Iv1.abcd1234efgh5678"
  # github_oauth_client_secret: "your-oauth-client-secret-here"
  
  # OAuth callback URL
  # Must match the callback URL configured in your OAuth App
  # Format: https://your-migrator-domain.com/api/v1/auth/callback
  # callback_url: "https://migrator.company.com/api/v1/auth/callback"
  
  # Frontend URL to redirect to after successful login
  # In production with integrated frontend/backend: use "/" (same domain)
  # In development with separate ports: use "http://localhost:3000"
  # Default: "http://localhost:3000"
  # frontend_url: "/"
  
  # Session secret key for JWT signing
  # MUST be a strong random string (32+ characters)
  # Generate with: openssl rand -base64 32
  # IMPORTANT: Keep this secret and don't commit to version control!
  # session_secret: "your-random-secret-key-at-least-32-characters-long"
  
  # Session duration in hours
  # How long users stay logged in before re-authentication required
  # Default: 24 (1 day)
  # session_duration_hours: 24
  
  # Authorization Rules (Optional)
  # Control WHO can access the system after authentication
  # If no rules are specified, any authenticated GitHub user can access
  # authorization_rules:
    # Require user to be member of specific organizations
    # User must be a member of AT LEAST ONE of these organizations
    # Leave empty to not require org membership
    # require_org_membership:
    #   - "my-company-org"
    #   - "migration-team-org"
    
    # Require user to be member of specific teams
    # User must be a member of AT LEAST ONE of these teams
    # Format: "organization/team-slug"
    # Team slugs are lowercase with hyphens (e.g., "platform-team")
    # Leave empty to not require team membership
    # require_team_membership:
    #   - "my-company-org/migration-admins"
    #   - "my-company-org/platform-team"
    
    # Require user to be an Enterprise administrator
    # If true, only GitHub Enterprise admins can access the system
    # Requires require_enterprise_slug to be set
    # Default: false
    # require_enterprise_admin: false
    
    # Enterprise slug for admin verification
    # Required only if require_enterprise_admin is true
    # This is the slug of your GitHub Enterprise
    # require_enterprise_slug: "my-enterprise"

# Example: Enabled authentication with org membership requirement
# auth:
#   enabled: true
#   github_oauth_client_id: "Iv1.abcd1234efgh5678"
#   github_oauth_client_secret: "${GITHUB_OAUTH_CLIENT_SECRET}"
#   callback_url: "https://migrator.company.com/api/v1/auth/callback"
#   session_secret: "${AUTH_SESSION_SECRET}"
#   session_duration_hours: 24
#   authorization_rules:
#     require_org_membership:
#       - "acme-corp"

# Example: Team-based access control
# auth:
#   enabled: true
#   github_oauth_client_id: "Iv1.abcd1234efgh5678"
#   github_oauth_client_secret: "${GITHUB_OAUTH_CLIENT_SECRET}"
#   callback_url: "https://migrator.company.com/api/v1/auth/callback"
#   session_secret: "${AUTH_SESSION_SECRET}"
#   session_duration_hours: 24
#   authorization_rules:
#     require_team_membership:
#       - "acme-corp/migration-team"
#       - "acme-corp/platform-engineering"

# Example: Enterprise admin only access
# auth:
#   enabled: true
#   github_oauth_client_id: "Iv1.abcd1234efgh5678"
#   github_oauth_client_secret: "${GITHUB_OAUTH_CLIENT_SECRET}"
#   callback_url: "https://migrator.company.com/api/v1/auth/callback"
#   session_secret: "${AUTH_SESSION_SECRET}"
#   session_duration_hours: 24
#   authorization_rules:
#     require_enterprise_admin: true
#     require_enterprise_slug: "acme-enterprise"

# =============================================================================
# Legacy GitHub Configuration (Deprecated)
# =============================================================================
# This section is maintained for backward compatibility only
# New deployments should use the source/destination format above

# github:
#   source:
#     base_url: "https://github.company.com/api/v3"
#     token: "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#   
#   destination:
#     base_url: "https://api.github.com"
#     token: "ghp_yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# =============================================================================
# Environment Variable Overrides
# =============================================================================
# All configuration values can be overridden with environment variables
# using the GHMIG_ prefix and uppercase keys with underscores
#
# Examples:
#   GHMIG_SERVER_PORT=8080
#   GHMIG_DATABASE_TYPE=postgres
#   GHMIG_DATABASE_DSN=postgres://...
#   GHMIG_SOURCE_TYPE=github
#   GHMIG_SOURCE_BASE_URL=https://...
#   GHMIG_SOURCE_TOKEN=ghp_...
#   GHMIG_DESTINATION_TYPE=github
#   GHMIG_DESTINATION_BASE_URL=https://...
#   GHMIG_DESTINATION_TOKEN=ghp_...
#   GHMIG_MIGRATION_WORKERS=10
#   GHMIG_MIGRATION_POLL_INTERVAL_SECONDS=30
#   GHMIG_MIGRATION_POST_MIGRATION_MODE=production_only
#   GHMIG_MIGRATION_DEST_REPO_EXISTS_ACTION=fail
#   GHMIG_LOGGING_LEVEL=info
#   GHMIG_LOGGING_FORMAT=json
#   GHMIG_LOGGING_OUTPUT_FILE=./logs/migrator.log
#   GHMIG_LOGGING_MAX_SIZE=100
#   GHMIG_LOGGING_MAX_BACKUPS=3
#   GHMIG_LOGGING_MAX_AGE=28
#
# See configs/env.example for a complete list of environment variables

# =============================================================================
# Notes
# =============================================================================
# 1. SUPPORTED MIGRATIONS:
#    - GitHub to GitHub migrations only
#    - Source: GitHub.com or GitHub Enterprise Server
#    - Destination: GitHub.com, GitHub with data residency, or GHEC EMU
#
# 2. AUTHENTICATION:
#    - PAT (Personal Access Token) is REQUIRED for migrations
#    - GitHub App authentication is OPTIONAL for discovery/profiling
#    - When both are configured: GitHub App used for discovery, PAT used for migrations
#    - Tokens MUST have organization admin access on both source and destination
#
# 3. DESTINATION ORGANIZATIONS:
#    - The destination organization for each repository can be customized per-repo
#      via the API or web interface (defaults to source organization name)
#
# 4. AUTHENTICATION (OPTIONAL):
#    - Authentication is DISABLED by default for backward compatibility
#    - Enable for production to control access via GitHub OAuth
#    - Supports org membership, team membership, or enterprise admin requirements
#    - See OPERATIONS.md for OAuth App setup instructions
#
# 5. SECURITY:
#    - Sensitive values (tokens, passwords, secrets) should use environment variables
#      rather than being stored in this file
#    - Never commit OAuth client secrets or session secrets to version control
#    - Use strong random strings for session_secret (32+ characters)
#
# 6. PRODUCTION:
#    - Use PostgreSQL instead of SQLite for production deployments
#    - Enable authentication with appropriate authorization rules
#    - Log rotation happens automatically - no need to configure logrotate

