server:
  port: 8080

database:
  type: sqlite
  dsn: ./data/migrator.db

# Source repository system (where to migrate FROM)
# Supported types: github, gitlab, azuredevops
source:
  type: github
  base_url: "https://github.company.com/api/v3"  # GitHub Enterprise Server
  token: "${GITHUB_SOURCE_TOKEN}"
  
  # GitHub App authentication (optional, for non-migration operations)
  # When configured, App tokens are used for discovery/profiling; PAT is used for migrations
  # app_id: 123456
  # app_private_key: "/path/to/private-key.pem"  # or inline PEM string
  # app_installation_id: 789012

# Destination repository system (where to migrate TO)
# Supported types: github, gitlab
# Note: Destination organization is determined per-repository, defaulting to source org
destination:
  type: github
  base_url: "https://api.github.com"  # GitHub Enterprise Cloud or GitHub.com
  token: "${GITHUB_DEST_TOKEN}"
  
  # GitHub App authentication (optional, for non-migration operations)
  # When configured, App tokens are used for discovery/profiling; PAT is used for migrations
  # app_id: 123456
  # app_private_key: "/path/to/private-key.pem"  # or inline PEM string
  # app_installation_id: 789012

# Migration worker configuration
migration:
  # Number of parallel migration workers (default: 5)
  workers: 5
  # Polling interval in seconds (default: 30)
  poll_interval_seconds: 30
  # When to run post-migration validation: never, production_only, dry_run_only, always (default: production_only)
  post_migration_mode: "production_only"
  # What to do if destination repo exists: fail, skip, delete (default: fail)
  dest_repo_exists_action: "fail"

logging:
  level: debug
  format: json
  output_file: ./logs/migrator.log
  max_size: 100
  max_backups: 3
  max_age: 28
