server:
  port: 8080

database:
  type: sqlite
  dsn: ./data/migrator.db

github:
  source:
    base_url: "https://github.company.com/api/v3"  # GitHub Enterprise Server
    token: "${GITHUB_SOURCE_TOKEN}"
  destination:
    base_url: "https://api.github.com"  # GitHub Enterprise Cloud
    token: "${GITHUB_DEST_TOKEN}"

logging:
  level: info
  format: json
  output_file: ./logs/migrator.log
  max_size: 100
  max_backups: 3
  max_age: 28
