server:
  port: 8080

database:
  type: sqlite
  dsn: ./data/migrator.db

# Source repository system (where to migrate FROM)
# Supported types: github, gitlab, azuredevops
source:
  type: github
  base_url: "https://github.company.com/api/v3"  # GitHub Enterprise Server
  token: "${GITHUB_SOURCE_TOKEN}"

# Destination repository system (where to migrate TO)
# Supported types: github, gitlab
destination:
  type: github
  base_url: "https://api.github.com"  # GitHub Enterprise Cloud or GitHub.com
  token: "${GITHUB_DEST_TOKEN}"

logging:
  level: info
  format: json
  output_file: ./logs/migrator.log
  max_size: 100
  max_backups: 3
  max_age: 28
