# GitHub Migration Server - Development Configuration
# This configuration is optimized for local development

server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s

database:
  # Use SQLite for development
  type: sqlite
  dsn: ./data/migrator.db

# Source repository system configuration
# Supported types: github, gitlab, azuredevops
source:
  type: github  # Change to 'gitlab' or 'azuredevops' for other platforms
  base_url: "https://github.company.com/api/v3"
  token: "${GITHUB_SOURCE_TOKEN}"
  # For Azure DevOps, also specify:
  # organization: "your-org-name"
  # username: "your-username"  # Optional

# Destination repository system configuration
# Supported types: github, gitlab
destination:
  type: github
  base_url: "https://api.github.com"
  token: "${GITHUB_DEST_TOKEN}"

# Legacy GitHub-specific configuration (if needed for backward compatibility)
# The source/destination format above is preferred
github:
  source:
    graphql_url: "https://github.company.com/api/graphql"
  
  destination:
    graphql_url: "https://api.github.com/graphql"
  
  rate_limit:
    requests_per_hour: 5000
    wait_on_exhaustion: true
  
  retry:
    max_attempts: 3
    initial_backoff: 1s
    max_backoff: 30s

logging:
  level: debug  # Verbose logging for development
  format: text  # Human-readable format
  output_file: ./logs/migrator.log
  max_size: 100
  max_backups: 3
  max_age: 7
  compress: false

migration:
  parallel_workers: 3
  timeout: 30m
  dry_run_default: true

discovery:
  parallel_workers: 5
  profile_depth: full
  timeout: 1h

batch:
  max_batch_size: 50
  execution_strategy: sequential

monitoring:
  enabled: false

security:
  cors_enabled: true
  cors_allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"

features:
  self_service_enabled: true
  batch_management_enabled: true
  analytics_enabled: true
  webhooks_enabled: false

