# GitHub Migrator - Development Configuration
# This configuration is optimized for local development

server:
  port: 8080

database:
  # Use SQLite for development
  type: sqlite
  dsn: ./data/migrator.db

# Source repository system configuration
# Only GitHub to GitHub migrations are supported
# Source: GitHub.com or GitHub Enterprise Server
source:
  type: github
  base_url: "${GITHUB_SOURCE_URL}"
  token: "${GITHUB_SOURCE_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # Provides better rate limits for discovery operations
  # When configured: GitHub App used for discovery, PAT used for migrations
  # 
  # app_installation_id is OPTIONAL:
  #   - Provide installation ID: Uses that installation's token for all operations
  #   - Omit installation ID: Auto-discovers all app installations, creates per-org clients
  #     (best for multi-org GitHub Apps, uses JWT auth for discovery)
  # 
  # app_id: 123456
  # app_private_key: "/path/to/private-key.pem"
  # app_installation_id: 789012  # Optional: omit for auto-discovery

# Destination repository system configuration
# Only GitHub to GitHub migrations are supported
# Destination: GitHub.com, GitHub with data residency, or GitHub Enterprise Server
destination:
  type: github
  base_url: "${GITHUB_DEST_URL:-https://api.github.com}"
  token: "${GITHUB_DEST_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # Provides better rate limits for discovery operations
  # When configured: GitHub App used for discovery, PAT used for migrations
  # 
  # app_installation_id is OPTIONAL:
  #   - Provide installation ID: Uses that installation's token for all operations
  #   - Omit installation ID: Auto-discovers all app installations, creates per-org clients
  #     (best for multi-org GitHub Apps, uses JWT auth for discovery)
  # 
  # app_id: 123456
  # app_private_key: "/path/to/private-key.pem"
  # app_installation_id: 789012  # Optional: omit for auto-discovery

# Migration worker configuration
migration:
  # Fewer workers for development to reduce rate limit usage
  workers: 3
  poll_interval_seconds: 30
  post_migration_mode: "production_only"
  dest_repo_exists_action: "fail"
  
  # Visibility transformation rules (default: all repos become private)
  visibility_handling:
    public_repos: "private"
    internal_repos: "private"

# Development logging - verbose and human-readable
logging:
  level: debug  # Verbose logging for development
  format: text  # Human-readable format
  output_file: ./logs/migrator.log
  max_size: 100
  max_backups: 3
  max_age: 7  # Shorter retention for dev

# Authentication (disabled for development)
# See OPERATIONS.md for setup instructions
auth:
  enabled: false
  # frontend_url: "http://localhost:3000"  # Uncomment and set when enabling auth in dev
