# GitHub Migrator - Docker Configuration
# This configuration is optimized for Docker deployments
# All values can be overridden via environment variables with GHMIG_ prefix
# Example: GHMIG_SOURCE_TOKEN will override source.token

server:
  port: 8080

database:
  # Values will be overridden by GHMIG_DATABASE_TYPE and GHMIG_DATABASE_DSN env vars
  type: sqlite
  dsn: /app/data/migrator.db

# Source repository system configuration
# Only GitHub to GitHub migrations are supported
# Source: GitHub.com or GitHub Enterprise Server
source:
  type: github
  base_url: https://api.github.com
  token: ""  # REQUIRED - Set via GHMIG_SOURCE_TOKEN environment variable
  
  # GitHub App authentication (optional for discovery/profiling)
  # Provides better rate limits for discovery operations
  # When configured: GitHub App used for discovery, PAT used for migrations
  # 
  # app_installation_id is OPTIONAL:
  #   - Provide installation ID: Uses that installation's token for all operations
  #   - Omit installation ID: Auto-discovers all app installations, creates per-org clients
  #     (best for multi-org GitHub Apps, uses JWT auth for discovery)
  # 
  # app_id: "${GHMIG_SOURCE_APP_ID}"
  # app_private_key: "${GHMIG_SOURCE_APP_PRIVATE_KEY}"
  # app_installation_id: "${GHMIG_SOURCE_APP_INSTALLATION_ID}"  # Optional

# Destination repository system configuration
# Only GitHub to GitHub migrations are supported
# Destination: GitHub.com, GitHub with data residency, or GitHub Enterprise Server
destination:
  type: github
  base_url: https://api.github.com
  token: ""  # REQUIRED - Set via GHMIG_DESTINATION_TOKEN environment variable
  
  # GitHub App authentication (optional for discovery/profiling)
  # Provides better rate limits for discovery operations
  # When configured: GitHub App used for discovery, PAT used for migrations
  # 
  # app_installation_id is OPTIONAL:
  #   - Provide installation ID: Uses that installation's token for all operations
  #   - Omit installation ID: Auto-discovers all app installations, creates per-org clients
  #     (best for multi-org GitHub Apps, uses JWT auth for discovery)
  # 
  # app_id: "${GHMIG_DEST_APP_ID}"
  # app_private_key: "${GHMIG_DEST_APP_PRIVATE_KEY}"
  # app_installation_id: "${GHMIG_DEST_APP_INSTALLATION_ID}"  # Optional

# Migration worker configuration
# Values will be overridden by GHMIG_MIGRATION_* environment variables
migration:
  workers: 5
  poll_interval_seconds: 30
  post_migration_mode: production_only
  dest_repo_exists_action: fail
  visibility_handling:
    public_repos: private
    internal_repos: private

# Docker logging configuration
# Values will be overridden by GHMIG_LOGGING_* environment variables
logging:
  level: info
  format: json
  output_file: /app/logs/migrator.log
  max_size: 200
  max_backups: 5
  max_age: 30

# Authentication (disabled by default for Docker)
# See OPERATIONS.md for setup instructions
# Values will be overridden by GHMIG_AUTH_* environment variables
auth:
  enabled: false
  github_oauth_client_id: ""
  github_oauth_client_secret: ""
  callback_url: ""
  frontend_url: /
  session_secret: ""
  session_duration_hours: 24
  authorization_rules:
    require_org_membership: []
    require_team_membership: []
    require_enterprise_admin: false
    require_enterprise_slug: ""
