# GitHub Migrator - Docker Configuration
# This configuration is optimized for Docker deployments

server:
  port: 8080

database:
  # Can be overridden with environment variables
  type: "${GHMIG_DATABASE_TYPE:-sqlite}"
  dsn: "${GHMIG_DATABASE_DSN:-/app/data/migrator.db}"

# Source repository system configuration
# Only GitHub to GitHub migrations are supported
# Source: GitHub.com or GitHub Enterprise Server
source:
  type: "${GHMIG_SOURCE_TYPE:-github}"
  base_url: "${GITHUB_SOURCE_URL:-https://github.company.com/api/v3}"
  token: "${GITHUB_SOURCE_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # app_id: "${GHMIG_SOURCE_APP_ID}"
  # app_private_key: "${GHMIG_SOURCE_APP_PRIVATE_KEY}"
  # app_installation_id: "${GHMIG_SOURCE_APP_INSTALLATION_ID}"

# Destination repository system configuration
# Only GitHub to GitHub migrations are supported
# Destination: GitHub.com, GitHub with data residency, or GitHub Enterprise Server
destination:
  type: "${GHMIG_DESTINATION_TYPE:-github}"
  base_url: "${GITHUB_DEST_URL:-https://api.github.com}"
  token: "${GITHUB_DEST_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # app_id: "${GHMIG_DEST_APP_ID}"
  # app_private_key: "${GHMIG_DEST_APP_PRIVATE_KEY}"
  # app_installation_id: "${GHMIG_DEST_APP_INSTALLATION_ID}"

# Migration worker configuration
migration:
  workers: "${GHMIG_MIGRATION_WORKERS:-5}"
  poll_interval_seconds: "${GHMIG_MIGRATION_POLL_INTERVAL_SECONDS:-30}"
  post_migration_mode: "${GHMIG_MIGRATION_POST_MIGRATION_MODE:-production_only}"
  dest_repo_exists_action: "${GHMIG_MIGRATION_DEST_REPO_EXISTS_ACTION:-fail}"

# Docker logging configuration
logging:
  level: "${GHMIG_LOGGING_LEVEL:-info}"
  format: "${GHMIG_LOGGING_FORMAT:-json}"
  output_file: "${GHMIG_LOGGING_OUTPUT_FILE:-/app/logs/migrator.log}"
  max_size: "${GHMIG_LOGGING_MAX_SIZE:-200}"
  max_backups: "${GHMIG_LOGGING_MAX_BACKUPS:-5}"
  max_age: "${GHMIG_LOGGING_MAX_AGE:-30}"
