# GitHub Migrator - Docker Configuration
# This configuration is optimized for Docker deployments

server:
  port: 8080

database:
  # Can be overridden with environment variables
  type: "${GHMIG_DATABASE_TYPE:-sqlite}"
  dsn: "${GHMIG_DATABASE_DSN:-/app/data/migrator.db}"

# Source repository system configuration
# Only GitHub to GitHub migrations are supported
# Source: GitHub.com or GitHub Enterprise Server
source:
  type: "${GHMIG_SOURCE_TYPE:-github}"
  base_url: "${GITHUB_SOURCE_URL:-https://github.company.com/api/v3}"
  token: "${GITHUB_SOURCE_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # Provides better rate limits for discovery operations
  # When configured: GitHub App used for discovery, PAT used for migrations
  # 
  # app_installation_id is OPTIONAL:
  #   - Provide installation ID: Uses that installation's token for all operations
  #   - Omit installation ID: Auto-discovers all app installations, creates per-org clients
  #     (best for multi-org GitHub Apps, uses JWT auth for discovery)
  # 
  # app_id: "${GHMIG_SOURCE_APP_ID}"
  # app_private_key: "${GHMIG_SOURCE_APP_PRIVATE_KEY}"
  # app_installation_id: "${GHMIG_SOURCE_APP_INSTALLATION_ID}"  # Optional

# Destination repository system configuration
# Only GitHub to GitHub migrations are supported
# Destination: GitHub.com, GitHub with data residency, or GitHub Enterprise Server
destination:
  type: "${GHMIG_DESTINATION_TYPE:-github}"
  base_url: "${GITHUB_DEST_URL:-https://api.github.com}"
  token: "${GITHUB_DEST_TOKEN}"  # REQUIRED for migrations
  
  # GitHub App authentication (optional for discovery/profiling)
  # Provides better rate limits for discovery operations
  # When configured: GitHub App used for discovery, PAT used for migrations
  # 
  # app_installation_id is OPTIONAL:
  #   - Provide installation ID: Uses that installation's token for all operations
  #   - Omit installation ID: Auto-discovers all app installations, creates per-org clients
  #     (best for multi-org GitHub Apps, uses JWT auth for discovery)
  # 
  # app_id: "${GHMIG_DEST_APP_ID}"
  # app_private_key: "${GHMIG_DEST_APP_PRIVATE_KEY}"
  # app_installation_id: "${GHMIG_DEST_APP_INSTALLATION_ID}"  # Optional

# Migration worker configuration
migration:
  workers: "${GHMIG_MIGRATION_WORKERS:-5}"
  poll_interval_seconds: "${GHMIG_MIGRATION_POLL_INTERVAL_SECONDS:-30}"
  post_migration_mode: "${GHMIG_MIGRATION_POST_MIGRATION_MODE:-production_only}"
  dest_repo_exists_action: "${GHMIG_MIGRATION_DEST_REPO_EXISTS_ACTION:-fail}"
  
  # Visibility transformation rules (default: all repos become private)
  visibility_handling:
    public_repos: "${GHMIG_MIGRATION_VISIBILITY_PUBLIC_REPOS:-private}"
    internal_repos: "${GHMIG_MIGRATION_VISIBILITY_INTERNAL_REPOS:-private}"

# Docker logging configuration
logging:
  level: "${GHMIG_LOGGING_LEVEL:-info}"
  format: "${GHMIG_LOGGING_FORMAT:-json}"
  output_file: "${GHMIG_LOGGING_OUTPUT_FILE:-/app/logs/migrator.log}"
  max_size: "${GHMIG_LOGGING_MAX_SIZE:-200}"
  max_backups: "${GHMIG_LOGGING_MAX_BACKUPS:-5}"
  max_age: "${GHMIG_LOGGING_MAX_AGE:-30}"

# Authentication (disabled by default for Docker)
# See OPERATIONS.md for setup instructions
auth:
  enabled: "${GHMIG_AUTH_ENABLED:-false}"
  github_oauth_client_id: "${GITHUB_OAUTH_CLIENT_ID}"
  github_oauth_client_secret: "${GITHUB_OAUTH_CLIENT_SECRET}"
  callback_url: "${GITHUB_OAUTH_CALLBACK_URL}"
  frontend_url: "${GHMIG_AUTH_FRONTEND_URL:-/}"  # URL to redirect after login (use "/" for integrated frontend)
  session_secret: "${AUTH_SESSION_SECRET}"
  session_duration_hours: "${GHMIG_AUTH_SESSION_DURATION_HOURS:-24}"
